### ISSUE TITLE
JackTrip "Unable to determine external IP address"

### ISSUE THREAD

**Issue by Trevor12341234** [jacktrip/jacktrip#515] opened 2022-03-24 01:51 UTC
I've tried installing and changing settings and I can't get my IP address to show up in this version of Jacktrip, any tips? I'm running Windows 10

**Comment by ntonnaett** [comment] 2022-03-24 17:36
What do you mean with this version of JackTrip?

**Comment by Trevor12341234** [comment] 2022-03-24 17:48
Version 1.5.2 and 1.5.1 I have this happening, before this I’ve only used 1.3.0 I believe.

**Comment by SynthiaPayne** [comment] 2022-03-24 21:00
same here - running Windows 11. Back in December, I asked Aaron about it 
and he said:

github builds are statically linked, and maybe the SSL library isn't being linked in for some reason.

synthia

**Comment by psiborg112** [comment] 2022-03-24 22:23
The GUI uses the [ipify API](https://www.ipify.org/) to determine the external IP address of your internet connection. If it can't determine your IP that means that traffic isn't making it through to the site. So, it's either a network issue or it fails because it's an https site and it can't find the SSL library. If you can try the build at [my site](https://www.psi-borg.org/other-dev.html) that will show us whether it's an issue that's crept into our build settings here or whether it's something else.

**Comment by ntonnaett** [comment] 2022-03-24 22:53
This address isn't part of the api:
https://github.com/jacktrip/jacktrip/blob/a594e335f58da0af9bb094fe6537bd37db0d8acd/src/gui/qjacktrip.cpp#L227

We might just use api64.

**Comment by psiborg112** [comment] 2022-03-24 23:16
Interesting. It used to be and still works as expected. We could change to 64 in the future, but will need to check that it returns something that isn't just a duplicate of the IPv4 address.

**Comment by psiborg112** [comment] 2022-03-24 23:18
And some of the libraries that they link to on their page still use it, so hopefully that means they're not planning to deprecate it any time soon.

**Comment by ntonnaett** [comment] 2022-03-24 23:18
api6 doesn't work for me. So IPv6 might be the culprit. api64 returns an v4 or v6 address.

**Comment by ntonnaett** [comment] 2022-03-24 23:20
Oh, it might just not work for me because of the IPv6 setup of my internet provider.

**Comment by psiborg112** [comment] 2022-03-24 23:26
Looks like I'm already checking whether our IPv6 address is a duplicate of our IPv4 address. So I guess it would be safe to change it to api64. Maybe it's always returned either protocol and they've just renamed it to better reflect what it does (and kept api6 working for backwards compatibility).

**Comment by psiborg112** [comment] 2022-03-24 23:27
(Or maybe api6 is now genuinely an ipv6 only thing. It seems to only have AAAA records when I do a DNS lookup on it.)

**Comment by psiborg112** [comment] 2022-03-29 19:34
@Trevor12341234 did you have a chance to test the version I suggested to see if you still have the same problem?

**Comment by psiborg112** [comment] 2022-04-20 23:22
We're having a related SSL issue in the new virtual studio interface. OpenSSL isn't being statically linked into Qt. On mac and linux it's generally available in a consistent location, so it's being loaded dynamically without issue, but this isn't the case on windows. We have two ways around this: we could either include the openssl dll in the installer package or we could use -openssl-linked in our configuration options when building static Qt. @dyfer and @ntonnaett, what are your thoughts on this?

**Comment by dyfer** [comment] 2022-04-21 02:44
I think the dll in the installer would be a bit more elegant, but I don't have a strong feeling about it. Let me know if I can help from the CI side of this.

**Comment by mattahorton** [comment] 2022-04-27 16:13
Addressed in #543

**Closed** 2022-06-01 16:10 UTC
