### ISSUE TITLE
"-r" flag does not work in HUB mode

### ISSUE THREAD

**Issue by DJ-FraktL** [jacktrip/jacktrip#160] opened 2020-09-16 02:24 UTC
In the following configuration the client and server connect and show cross wiring in jackd. Audio only flows from client to server, not vice versa. When the "-r 4" toggle is removed from both client and server command line (with no other changes) everything works as expected. 
Suggest either correction to operation to allow multiple routing or update manual to identify that "-r" not usable with HUB mode. 

Client command line:
jacktrip -o10 -n 2 -r 4 -q 20 -z -C <IP>

Server command line:
jacktrip -o10 -n 2 -r 4 -q 20 -z -S -p0

**Comment by ntonnaett** [comment] 2021-01-21 23:15
Might be a duplicate of #41 . Could you try version 1.3.0?

**Comment by ntonnaett** [comment] 2021-03-18 19:23
Closing because there was no response. Might just be a bandwidth problem.

**Closed by ntonnaett** 2021-03-18 19:23 UTC
