### ISSUE TITLE
OSX version only works up to macOS El Capitan with JackRouter 0.92 b3

### ISSUE THREAD

**Issue by ghost** [jacktrip/jacktrip#32] opened 2017-11-23 14:30 UTC
## Greetings

**I would like to point out that:**
- *OSX current release only works up to macOS El Capitan with JackRouter 0.92 b3*

---

**that means that:**
- *there are some broken dependencies that are macOS version related, that need to be fixed, in order for the program to properly execute*

---

**the only way to currently run jacktrip is to:**
- *Install the latest release dating from 2015 (two years old)*
- *get El Capitan*;
- *get Jackrouter 0.92 b3*
- *getting the latest JackTrip release*

**i should also notice that:**
- *it doesn't allow you to install jacktrip to bin folder, but you can run it locally (i tried it cp with sudo command and it wouldn't work)*
- *there should be a script that temporarily brute forces system integrity to allow the installation of the program*

**Comment by ntonnaett** [comment] 2020-06-07 16:11
Duplicate of #60

**Closed by ntonnaett** 2020-06-07 16:11 UTC
