### ISSUE TITLE
Latency Measurement -x

### ISSUE THREAD

**Issue by upretyrohan** [jacktrip/jacktrip#524] opened 2022-03-31 11:26 UTC
What is " cumulative mean and standard-deviation ("statistics") are computed", 

I see this printed on the screen many times : is this the o/p from user point of view
" AudioTester.h: computeProcessFromNetwork: Received pulse amplitude 0.00756836 (cell 1) while looking for cell 8"

and sometimes this

209.1 [589.5] 
[20-25ms]=  7:*******
[25-30ms]=  1:*
[30-35ms]=  9:*********
[35-40ms]=  4:****
[40-45ms]=  1:*
[45-50ms]=  0:
[50-55ms]=  0:
[55-60ms]=  0:
[60-65ms]=  0:
[65-70ms]=  0:
[70-75ms]=  0:
[75-80ms]=  0:
[80-85ms]=  0:
[85-90ms]=  0:
[90-95ms]=  1:*
[95-100ms]=  3:***
 and above

How to interpret this data?

How can i get just get the round trip time taken
if i want to measure latency

**Comment by upretyrohan** [comment] 2022-03-31 11:32
I see this : is this the o/p from user point of view
 AudioTester.h: computeProcessFromNetwork: Received pulse amplitude 0.00756836 (cell 1) while looking for cell 8

**Comment by ntonnaett** [comment] 2022-04-07 20:16
Duplicate of #448

**Closed by ntonnaett** 2022-04-07 20:16 UTC
