### ISSUE TITLE
UDP timeout not working

### ISSUE THREAD

**Issue by kgokalp** [jacktrip/jacktrip#474] opened 2022-01-21 08:31 UTC
When __MANUAL_POLL__ is not defined as default case, "Disconnect after 10 seconds of no network activity" option is not working as intended. I tested on version 1.5.1.

**Comment by psiborg112** [comment] 2022-01-21 11:18
I can't recreate this. I'm going to need more info. What operating system is this on? And what mode is this in? (Hub/P2P client/server)

**Comment by kgokalp** [comment] 2022-01-21 12:52
Operating system is debian buster. I tested on Hub client/server configuration. 
As I understand from debugging, epoll_wait function still returns 1 even if no data is available. So timeout case is not occurring.

**Comment by psiborg112** [comment] 2022-01-21 14:38
Weird. I'm on Debian Sid and epoll_wait is working as expected. What kernel version are you on?

**Comment by kgokalp** [comment] 2022-01-21 16:07
Kernel is different than default kernel, 5.10.0-9.1-liquorix-amd64.

**Comment by psiborg112** [comment] 2022-01-21 22:15
Might be worth trying with a stock kernel just to rule that out. How are you checking the return value of epoll_wait? Are you able to provide a step by step guide of how you're testing the issue?

**Comment by kgokalp** [comment] 2022-01-28 08:57
Tried with both kernels, result is same. But I think I found the reason. If server and client run on the same pc, timeout case is not occuring. If they run on seperate pc, everything is fine. Is that a problem to fix, or is it expected?

**Comment by psiborg112** [comment] 2022-01-28 09:08
No, that's not an expected result. I still cant reproduce the bug even with both instances running on the same machine. The timeout works as expected. Are you running the GUI or command line version? If the command line, what arguments are you using for server and client? If the GUI can you go to the advanced options tab for each instance, click on the "Get Command Line" button and paste the results here?

**Comment by kgokalp** [comment] 2022-01-28 11:37
I am running GUI from command line and command line arguments are like below

For client: jacktrip -C 127.0.0.1 -z -n 1 -t -q auto -B 4465 --udprt
For server: jacktrip -S -z -p 5 -q auto --udprt

I can reproduce the scenario by killing the server app with SIGKILL command. On client console,  no timeout messages are shown, only AutoQueue log with increased values like below

Waiting for Peer...
Received Connection from Peer!
AutoQueue: 3
AutoQueue: 3
AutoQueue: 3
AutoQueue: 24
AutoQueue: 151
AutoQueue: 252
AutoQueue: 332
.
.
.

**Comment by psiborg112** [comment] 2022-01-28 11:59
Thanks for doing that. The 127.0.0.1 seems to be what's doing it, but I have no idea why. Works as expected for me using localhost or ::1 as the address. It's only when using 127.0.0.1 that the problem seems to occur. Will need to investigate.

**Comment by psiborg112** [comment] 2022-01-28 13:00
Seems to effect MacOS as well. Using localhost or ::1 works as expected on the timeout front, but 127.0.0.1 doesn't.

**Comment by kgokalp** [comment] 2022-01-28 13:21
Same here. localhost is resolved as ::1, that is why it works. It seems like, it is IPv4 related.

**Comment by psiborg112** [comment] 2022-01-28 14:27
Thanks so much for bearing with me on that. The issue should now be fixed.

**Comment by kgokalp** [comment] 2022-01-28 15:22
It works like a charm. Thank you for quick response and fix.

**Comment by ntonnaett** [comment] 2022-01-28 22:14
Fixed with #481

**Closed by ntonnaett** 2022-01-28 22:14 UTC
