### ISSUE TITLE
Ubuntu 16.04.2LTS w/ jacktrip 1.1~repack-3: coredump on PtP

### ISSUE THREAD

**Issue by amsheppard** [jacktrip/jacktrip#28] opened 2017-07-30 07:58 UTC
Hello all -

Both systems using same repos for JACK, etc., ([KXStudio](http://kxstudio.linuxaudio.org/)) running [Elementary OS 0.4.1](https://elementary.io/) (Ubuntu 16.04.2 LTS derivative) though I believe jacktrip 1.1~repack-3 is [being pulled from Ubuntu's repos](https://packages.ubuntu.com/xenial/jacktrip).

**Server:** wrkstn00: ```Linux wrkstn00 4.4.0-83-lowlatency #106-Ubuntu SMP PREEMPT Mon Jun 26 18:42:13 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux```
**Client:** x220-eos: ```Linux x220-eos 4.4.0-87-lowlatency #110-Ubuntu SMP PREEMPT Tue Jul 18 13:54:56 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux```
```
ii  jacktrip                                       1.1~repack-3                                              amd64
```
```
dpkg -l | grep "jackd"
[ .. snip ... ]
ii  jackd                                          5                                                         all          JACK Audio Connection Kit (default server package)
ii  jackd2                                         2:1.9.11+git20170722-1~kxstudio2v5                        amd64        JACK Audio Connection Kit (server and example clients)
ii  libjack-jackd2-0:amd64                         2:1.9.11+git20170722-1~kxstudio2v5                        amd64        JACK Audio Connection Kit (libraries)
ii  pulseaudio-module-jack                         1:8.0-0ubuntu3.3                                          amd64        jackd modules for PulseAudio sound server
```
Peer to peer connection, no router, via Cat 6 straight through (ping responses as expected @ <0.30ms). Via [Cadence](http://kxstudio.linuxaudio.org/Applications:Cadence), both interfaces have same settings for Engine

- RT
- RT Priority 10
- Client timeout 500ms
- 256 port max
- HPET clock source 
- Don't restrict self connection requests

Both Drivers have same sample rate (48000), 256 buffer size, 3 periods per buffer.
```
wrkstn00:~$ jacktrip -s
Setting JACK Process Callback...
SUCCESS
---------------------------------------------------------
The Sampling Rate is: 48000
---------------------------------------------------------
The Audio Buffer Size is: 256 samples
                      or: 1024 bytes
---------------------------------------------------------
The Number of Channels is: 2
---------------------------------------------------------
Using UDP Protocol
---------------------------------------------------------
Waiting for Connection From Client...
Client Connection Received from IP : ::ffff:192.168.1.100
---------------------------------------------------------
SuspendRefNum error
JackClient::Execute error name = JackTrip
terminate called after throwing an instance of 'std::runtime_error'
  what():  The Jack Server was shut down!
Aborted (core dumped)

```
```
x220-eos:~$ jacktrip -c 192.168.1.101
Setting JACK Process Callback...
SUCCESS
---------------------------------------------------------
The Sampling Rate is: 48000
---------------------------------------------------------
The Audio Buffer Size is: 256 samples
                      or: 1024 bytes
---------------------------------------------------------
The Number of Channels is: 2
---------------------------------------------------------
Using UDP Protocol
---------------------------------------------------------
Peer Address set to: 192.168.1.101
---------------------------------------------------------
UDP Socket Receiving in Port: 4464
---------------------------------------------------------
Waiting for Peer...
SuspendRefNum error
JackClient::Execute error name = JackTrip
terminate called after throwing an instance of 'std::runtime_error'
  what():  The Jack Server was shut down!
Aborted (core dumped)
```
Please advise is further information need be provided. TIA.

**Comment by lachs0r** [comment] 2018-02-23 13:38
Same issue here on openSUSE Tumbleweed with jacktrip 1.1 built from source. Can’t get this to work at all.

**Comment by egelor** [comment] 2018-04-19 22:40
Same here Ubuntu 16.04 and Ubuntu 14

**Comment by Zer0-** [comment] 2019-02-23 02:02
Same here on NixOS 18.03, I built 2596fc2f9aab5ef0b1ddee3c95748d653d857d77 from source.

**Comment by bobemoe** [comment] 2019-09-05 09:51
Same here on Devuan using jacktrip 1.1~repack-5+b2

**Comment by brandflake11** [comment] 2019-12-05 14:41
Not to post on an old issue, but I am having this issue as well on Arch Linux with the latest everything.

**Comment by ave4** [comment] 2020-02-05 17:08
У меня тоже была эта проблема, но я попробовал собрать из ветки feature/code_maintenance и вроде всё заработало. I also had this problem, but I tried to collect **feature/code_maintenance** from the branch and everything seemed to work.

**Comment by Foaly** [comment] 2020-03-22 11:45
@ave4 Nice thats good to know! I will try to merge it soon. Maybe you could confirm after the merge that the current master is working for you, then I would close this issue :) Thanks for the info!

**Comment by Foaly** [comment] 2020-03-27 10:26
Closing this now, as there sees the recent changes seem to fix the bug. If the problem is still present, feel free to reopen the ticket :)

**Closed by Foaly** 2020-03-27 10:26 UTC
