### ISSUE TITLE
Windows: segfault in UdpDataProtocol::receivePacket (QUdpSocket)

### ISSUE THREAD

**Issue by tangmi** [jacktrip/jacktrip#117] opened 2020-08-06 05:45 UTC
Hi, I'm trying to run JackTrip v1.2.1 in hub mode on Windows 10 version 2004 (`jacktrip -S`) and have ports 4464 and 61000 open. When a client connects with `jacktrip -C <ip address>`, the server crashes almost immediately.

I've debugged the program in Qt Creator (qt 5.15.0, mingw 64-bit 8.1.0) and get a segfault somewhere on this line:: https://github.com/jacktrip/jacktrip/blob/v1.2.1/src/UdpDataProtocol.cpp#L323

The stack is as follows:

```
1 QNativeSocketEnginePrivate::nativeReceiveDatagram(char *, long long, QIpPacketHeader *, QFlags<QAbstractSocketEngine::PacketHeaderOption>)                         0x697aeb19     
2 QNativeSocketEngine::readDatagram(char *, long long, QIpPacketHeader *, QFlags<QAbstractSocketEngine::PacketHeaderOption>)                                         0x697ac5f1     
3 QUdpSocket::readDatagram(char *, long long, QHostAddress *, unsigned short *)                                                                                      0x697a0880     
4 UdpDataProtocol::receivePacket                                                                                                             UdpDataProtocol.cpp 323 0x40bfb1       
5 UdpDataProtocol::run                                                                                                                       UdpDataProtocol.cpp 521 0x40c599       
6 QThreadPrivate::start(void *)                                                                                                                                      0x68898eaa     
7 KERNEL32!BaseThreadInitThunk                                                                                                                                       0x7ff82cf76fd4 
8 ntdll!RtlUserThreadStart                                                                                                                                           0x7ff82d6dcec1 
9 ??                                                                                                                                                                                
```

The packet size `n` is 2064 and `buf` seems valid, so I'm unsure how to dig deeper since I am unable to step into Qt sources on Windows with MinGW (I think since it uses GDB instead of CDB). I'm not familiar with Qt Creator so please let me know if there's something I can do to step into the sources!

**Comment by psiborg112** [comment] 2020-08-06 06:17
The windows version has always been a little touchy after I made changes to the networking to enable IPv6. There were a few odd bugs that were hard to track down, and I suspect there's still something about the way we're using windows sockets and the way that Qt is using windows sockets that is conflicting. Are you able to try a build of the 'aaron' branch to see if the bug persists? (All of the QUdpSocket code has been replaced with winsock code.)

**Comment by tangmi** [comment] 2020-08-06 06:52
The `aaron` branch seems to work great! I had to fix a typo here https://github.com/jacktrip/jacktrip/blob/aaron/src/UdpDataProtocol.cpp#L833, but it otherwise works (maybe with lower latency than the QUdpSocket version? It may just be misremembering things). I'll update the title to reflect that its related to QUdpSocket.

**Comment by psiborg112** [comment] 2020-08-06 07:29
Gah, I thought I'd already fixed that typo. I really need to get better with github. I might try to isolate that networking change and push it to the main branch sooner rather than later.

**Comment by cchafe** [comment] 2020-08-07 16:40
I can't reproduce the segfault running "main" 1.2.1 in "-S -p1" mode.
What srate and FPP settings were used?

**Comment by tangmi** [comment] 2020-08-07 19:29
The fpp was 512 and the srate was 48000. I use portaudio with the ASIO driver for my Focusrite interface.

**Comment by cchafe** [comment] 2020-08-07 22:22
I tested with those settings and dummy driver and its fine. No Focusrite available.
This might or might not be a hint -- the only segfault I've seen (in recent memory) has been when the running jack version doesn't match what jacktrip was compiled against.

**Comment by psiborg112** [comment] 2020-08-07 23:38
I was getting the same segfault with the same qt version and mingw version under windows when building with the GUI additions, which is why I changed the code. (This has been in the qjacktrip and aaron branches for a while now.) I think it's related to the same issues that we were having previously under windows: there's something about the way that QUdpSocket and the windows sockets are interacting that's causing difficult to track issues that only seem to surface under certain circumstances.

**Comment by ntonnaett** [comment] 2020-09-08 22:01
Can this be closed?

**Comment by psiborg112** [comment] 2020-09-08 22:21
I really hope so. Seems to be fixed in dev.

**Comment by ntonnaett** [comment] 2020-09-08 22:22
Alright. So if it's not, just reopen it again!

**Closed by ntonnaett** 2020-09-08 22:22 UTC
