### ISSUE TITLE
JackTrip crashes on High Sierra on first launch

### ISSUE THREAD

**Issue by forsythac** [jacktrip/jacktrip#671] opened 2022-08-04 21:23 UTC
Followup from high sierra issue reported on https://github.com/jacktrip/jacktrip/issues/552 another user has encountered this crash when launching JackTrip GUI

MacOS v 10.13.6 High Sierra

![image](https://user-images.githubusercontent.com/3578658/182953784-e5b59ac1-d0ae-4692-b3d4-621c79353381.png)

this is the output of "Report"

[high_sierra_report.txt](https://github.com/jacktrip/jacktrip/files/9263384/high_sierra_report.txt)

any ideas on this one? I also can't find any firm recommendations about what the oldest supported MacOS version is.

**Comment by SynthiaPayne** [comment] 2022-08-04 21:39
does this help? scroll down to "Installing JackTrip"

https://ccrma.stanford.edu/software/jacktrip/osx/index.html

**Comment by OConnorStP** [comment] 2022-08-04 23:16
Picking up from the previous thread...

here's a copy of a similar crash report from my High Sierra machine.   https://www.dropbox.com/s/33sz0letl0lit3a/crash_report.txt

it's important to note that the current command-line version of Jacktrip still runs on High Sierra -- it's just the GUI version that's having trouble.  here's a Terminal dialog from a newly-installed copy of 1.6.1 (i don't have an interface on this headless Mac so JT complains about that).

> jacktrip -C 172.104.11.23
> *** WEAK-JACK: initializing
> *** WEAK-JACK: OK. (0)
> Cannot connect to server socket err = Connection refused
> Cannot connect to server request channel
> jackdmp 1.9.20
> Copyright 2001-2005 Paul Davis and others.
> Copyright 2004-2016 Grame.
> Copyright 2016-2021 Filipe Coelho.
> jackdmp comes with ABSOLUTELY NO WARRANTY
> This is free software, and you are welcome to redistribute it
> under certain conditions; see the file COPYING for details
> JACK server starting in realtime mode with priority 10
> self-connect-mode is "Don't restrict self connect requests"
> JACK output port = 0 ==> output channel = 0
> JACK output port = 1 ==> output channel = 1
> CoreAudio driver is running...
> JACK server started
> Setting JACK Process Callback...
> SUCCESS
> ---------------------------------------------------------
> The Sampling Rate is: 48000
> ---------------------------------------------------------
> The Audio Buffer Size is: 512 samples
>                       or: 2048 bytes
> ---------------------------------------------------------
> The Number of Channels is: 2
> ---------------------------------------------------------
> Using UDP Protocol
> ---------------------------------------------------------
> Using JitterBuffer strategy 1
> Server Address set to: 172.104.11.23 Port: 61002
> ---------------------------------------------------------
> UDP Socket Receiving in Port: 4464
> ---------------------------------------------------------
> Waiting for Peer...
> WARNING: Cannot find any physical capture ports
> Received Connection from Peer!


Synth, we should check in with Chris and see if he wants to update that installation page -- i think it's out of date.

**Comment by forsythac** [comment] 2022-08-05 20:59
I hope that 1.3.0 isn't the only JackTrip that works on High Sierra! Esp since the command line version works, the GUI may be fixable on that platform. Fingers crossed 🤞

**Comment by psiborg112** [comment] 2022-08-06 05:09
Hi Mike, would you be able to try my build of JackTrip from this link: [https://www.psi-borg.org/JackTrip.pkg](https://www.psi-borg.org/JackTrip.pkg)
I suspect it's a build issue where at least one of the component libraries is being built with a deployment target later than 10.13.

**Comment by OConnorStP** [comment] 2022-08-06 13:00
hi Aaron,

kewl!  

i just loaded it up and got a new version of the crash message.  here's a link to the actual crash report...

https://www.dropbox.com/s/1tpbwrcp06uqind/crash_report_PSIborg.txt

and here's the GUI message...
![crash_report_PSIborg](https://user-images.githubusercontent.com/11680527/183249911-a113fa3a-991e-4346-8c5c-efea1125eaef.jpg)

**Comment by psiborg112** [comment] 2022-08-06 13:23
Thanks Mike. Different issue but same result. I think one of my libraries must have updated to a non-universal binary, or something like that. Will take a look and get you to try again when I have sorted it. (Or at least when I think I have.)

**Comment by psiborg112** [comment] 2022-08-06 15:08
Are you able to try again Mike? Same link. You'll just need to re-download it. (Might want to clear your web cache first so that you can make sure it definitely downloads the new revision. Alternatively you could run the following command on the terminal to download it to the current directory: `curl https://www.psi-borg.org/JackTrip.pkg -o JackTrip.pkg`)

**Comment by OConnorStP** [comment] 2022-08-06 19:10
Good news!  That new version runs, successfully connects and successfully disconnects in GUI mode.

**Comment by psiborg112** [comment] 2022-08-07 00:03
Thanks for that Mike. So that points to a build issue, especially with ____chkstk_darwin not being found. (It's been a while since I've encountered this, but I think that may have been introduced in 10.14)

**Comment by psiborg112** [comment] 2022-08-07 02:31
Also, until the issue is sorted with the official build, feel free to recommend mine to anyone on High Sierra. The only caveats are that auto-updates won't be enabled, and the virtual studio interface isn't included. (So they're only useful for those connecting to servers manually.)

**Comment by OConnorStP** [comment] 2022-08-07 12:00
Great!  Thanks!  By the way, it also solved the problem that I was having on the issue that preceded this one (https://github.com/jacktrip/jacktrip/issues/552).  Jacktrip now quits/restarts cleanly on my M1 using either RT audio or Jack backends.

**Comment by forsythac** [comment] 2022-08-08 17:38
@psiborg112 how soon can we get the fix into the main build?

cc: @mattahorton @mikedickey @nwang92

**Comment by psiborg112** [comment] 2022-08-08 23:31
Unfortunately it's not quite that straight forward, and might be a question for @dyfer and @mattahorton who have done more work with GitHub actions and know the current state of it better than I do. My build process is very different - I'm using macports for Qt rather than homebrew, and building with cmake. Effectively it'll be a matter of checking that every component is being built with a MacOS deployment target of 10.13, but I'm not sure how that needs to be done with homebrew. (It's one variable in one file for macports.)

**Comment by psiborg112** [comment] 2022-08-08 23:34
The other key difference is that I'm using dynamic rather than static Qt, which really simplifies the build process, but complicates the app bundling process. And I'm hesitant to change anything relating to the current Qt build settings because I know we've had issues before when trying to include various Qt components. (@mattahorton is well versed in how annoying that situation was, and probably bore the brunt of it.)

**Comment by dyfer** [comment] 2022-08-09 03:28
Hello everyone,
Yes, this is due to the deployment target being set too high. This is likely the case for RtAudio (homebrew libs are built for 10.14+), but I also recall there might've been something about the static build of Qt 5.15. I remember that I briefly tried to make a 10.13-compatible build and failed, but I can't remember the reason.

I think the first step would be to use bundled RtAudio in our build matrix ([trivial change](https://github.com/jacktrip/jacktrip/blob/main/.github/workflows/jacktrip.yml#L103-L104), but the build needs to be tested to make sure it still works okay) and see if that helps.

**Comment by dyfer** [comment] 2022-08-10 01:45
@OConnorStP Would you be able to test [this build](https://github.com/jacktrip/jacktrip/actions/runs/2828839773) on a 10.13 machine? It includes the build fix I mentioned earlier. I'm not sure if that's enough though.

I suggest downloading the file [JackTrip-05b3267-macOS-x64-qmake-clang-static-application](https://github.com/jacktrip/jacktrip/suites/7742517151/artifacts/324954199) which is just the application bundle without an installer (it won't overwrite the current install), but of course you can also download the installer if preferred. 
As this is an unsigned build, you need to right-click-open it and you'll get the option to "open anyway" on the second attempt.

**Comment by OConnorStP** [comment] 2022-08-10 12:02
Works!!  Here's the Terminal transcript:

https://www.dropbox.com/s/kd05uf8z784xkqe/jacktrip.1.6.2.-rc.2_OSX10.13_test.txt

GUI version also works, as before.

**Comment by OConnorStP** [comment] 2022-08-10 12:20
I also tested on two M1's -- one is running Monterey 12.2 the other's at 12.5.  Here are the Terminal outputs.  They are still throwing the Semaphore errors, which may not be in the scope of the fix, just FYI

Monterey 10.2 transcript: https://www.dropbox.com/s/z2ptqaame26un08/jacktrip.1.6.2.-rc.2_OSX12.2_test.txt

Monterey 10.5 transcript: https://www.dropbox.com/s/6y3necwjd3eiozq/jacktrip.1.6.2.-rc.2_OSX12.5_test.txt

**Comment by dyfer** [comment] 2022-08-10 15:24
@OConnorStP thanks so much for testing! I'll update the PR shortly.

Re: Semaphore errors - correct, the build fix for 10.13 won't address these.

**Comment by psiborg112** [comment] 2022-08-11 04:19
Or anything we do really. The semaphore warnings/errors are JACK things.

**Comment by dyfer** [comment] 2022-08-11 16:50
I believe https://github.com/jacktrip/jacktrip/pull/681 closed this.

**Closed by dyfer** 2022-08-11 16:50 UTC
Labels: bug
