### ISSUE TITLE
Command line parse error in audiodevices

### ISSUE THREAD

**Issue by maingig** [jacktrip/jacktrip#843] opened 2022-12-11 20:11 UTC
jacktrip -C cm-toast.stanford.edu -z --udprt --rtaudio --srate 48000 --bufsize 128 --audiodevice "Rogue Amoeba Software, Inc.: Loopback Audio 2", "Rogue Amoeba Software,Inc.: Loopback Audio 1" -B 4494 --overflowlimiting ow -n2 -z -q 8
*** WEAK-JACK: initializing
*** WEAK-JACK: OK. (0)
ERROR:
Found multiple commas in the --audiodevice argument, cannot parse reliably.

It should be looking for the entire quoted string before a comma.

**Comment by ntonnaett** [comment] 2022-12-11 22:19
Duplicate of #495

**Closed by ntonnaett** 2022-12-11 22:19 UTC
