### ISSUE TITLE
Crackling audio on MacOS - Seems priority/performance related

### ISSUE THREAD

**Issue by mattahorton** [jacktrip/jacktrip#504] opened 2022-03-08 15:56 UTC
Hey folks,

Since I've mostly moved my JackTrip use to the GUI, I and many people who have been on JackTrip servers with me have noticed crackling audio. From my testing, it seems to be an issue only on MacOS and is far less likely to happen when JackTrip is the only thing running. I particularly notice it when I am also on Zoom and change the size of my Zoom window, but window management in general affects it.

Did we change something recently that might have affected priority of the JackTrip process or some other thing affecting performance?

**Comment by dyfer** [comment] 2022-03-10 22:14
As I just experience during the JT dev call - I've had an issue on macOS with crackling that was caused by using separate input and output device that do not share a clock (i.e. built-in microphone and FW audio interface as an output). Can you confirm the audio devices you used when noticing this problem? And whether you used RtAudio or JACK?

**Comment by mattahorton** [comment] 2022-03-10 22:55
Yep. I technically use the same device but the input I use through a virtual device created by Loopback. So to the OS, I am using a separate input and output device.

**Comment by dyfer** [comment] 2022-03-10 22:58
I'm not sure I follow. Does JT use Loopback as both input and output device?

**Comment by mattahorton** [comment] 2022-03-11 15:21
No. I use my Scarlett as output. Loopback as input. But the loopback device just maps my Scarlett input to dual mono.

**Comment by mattahorton** [comment] 2022-03-11 19:21
Yep. it's on my todo list.

**Comment by OConnorStP** [comment] 2022-10-11 08:14
hi Matt,

there's a handy tool in the GUI to help you answer the age-old question "what has changed?"  take a look in the Advanced options tab for the "Get Command Line" button.  that will show you the command line that the GUI is going to use to connect to Jacktrip.  compare that command line to the one you used to use when there weren't any crackles and see if that gives you any ideas.

in the same vein, try running Jacktrip from the command line (with the old string) and see if things improve.

mike

**Comment by ntonnaett** [comment] 2023-01-27 19:35
That's most likely not a thing anymore. Closing this.

**Closed by ntonnaett** 2023-01-27 19:35 UTC
