### ISSUE TITLE
1.6.2 - Hub Server seg_faults when launched from Terminal on Mac/PC

### ISSUE THREAD

**Issue by OConnorStP** [jacktrip/jacktrip#702] opened 2022-08-21 12:33 UTC
Here's a link to a discussion in the User group that demonstrates the problem - launching a Hub server from the command line seg_faults.

https://groups.google.com/g/jacktrip-users/c/UnKrnKhKlpM/m/pJ5o8aECAQAJ

I ran a more complete series of tests this morning on the four Macs.  I ran through launching all four client and server modes and demonstrated pretty much identical results.  Hub and non-Hub client connections are fine.  Non-hub server is fine.  Hub server isn't.  Here are the four tests -- terminal log followed by crash report in each.

https://www.dropbox.com/s/5l5pw346v0eshae/jacktrip.1.6.2_seg-fault_Intel_OSX10.13.6.txt
https://www.dropbox.com/s/kiq4ni11h7y9b5u/jacktrip.1.6.2_seg-fault_Intel_OSX12.4.txt
https://www.dropbox.com/s/x7yliixf8c3qlax/jacktrip.1.6.2_seg-fault_M1_OSX12.2.txt
https://www.dropbox.com/s/0udr519nlvml9m2/jacktrip.1.6.2_seg-fault_M1_OSX12.5.1.txt

Let me know if I can help by running different versions of the tests.

**Comment by psiborg112** [comment] 2022-08-21 13:47
This seems to be a problem specific to builds that include all of the VS stuff. It's the following line in UdpHubListener.cpp that's causing the issue:
```
qDebug() << "mThreadPool default maxThreadCount =" << QThread::idealThreadCount();
```
It looks innocuous by itself. But my guess is that it's a problem caused by the qtMessageHandler for writing to a log file introduced in main.cpp if NO_VS isn't defined. I'm guessing that the standard qDebug handlers have overridden "<<" operators for integers, while the one being provided for the log file expects a QString const&.

(Because my builds are NO_VS builds, they are not affected by this issue.)

**Comment by psiborg112** [comment] 2022-08-21 14:18
To whoever takes this bug on, there are two potential fixes, one of which is a bad idea. It would be possible to explicitly convert QThread::idealThreadCount() to a QString, but this is asking for the issue to pop up somewhere else down the line. The right way to fix it would be to make sure that the custom qtMessageHandler can deal with integer input without crashing.

**Comment by psiborg112** [comment] 2022-08-21 15:21
OK, tried the lazy way of fixing it to see if that at least solved the problem, but it did not. Seems that any data type sent to qDebug will cause the issue. Commenting out the two qDebug statements in the UdpHubListener constructor fixes the problem you're currently seeing. If I add a qDebug statement before the qInstallMessageHandler(qtMessageHandler) call in main.cpp it works fine. If I add one after it, it prints what's sent to it and then segfaults.

And I've found the problem. You're using an uninitialised pointer - the textStream (ts) isn't created when not using the GUI. Since you're only attempting to open the log file when launching the GUI, the sensible fix seems to be to not install the qtMessageHandler when in GUI mode. Addressed in #704. This is a pretty major bug and should be addressed in a point release asap.

**Comment by psiborg112** [comment] 2022-08-21 15:23
I hope you've enjoyed my one man monologue, _Diary of a Segfault_. You've been a wonderful audience.

**Comment by OConnorStP** [comment] 2022-08-21 15:31
I've enjoyed every post of your monologue.  And agree -- not being able to launch Hub servers from the command line is a big deal (speaking as one who does that a lot).  Thanks for diving in, Aaron.

**Comment by ntonnaett** [comment] 2022-08-21 19:39
Should we add a clang-tidy check for uninitialized pointers/variables?

**Comment by psiborg112** [comment] 2022-08-21 21:40
@ntonnaett, it might not hurt to include one.

**Comment by mattahorton** [comment] 2022-08-22 21:26
Given this fix (thanks @psiborg112) should we go ahead and start prepping 1.6.3?

**Closed** 2022-08-23 21:54 UTC
Labels: bug
