### ISSUE TITLE
1.6.3 GUI throws error on Debian 11

### ISSUE THREAD

**Issue by OConnorStP** [jacktrip/jacktrip#731] opened 2022-09-09 23:11 UTC
1.5.3 Terminal and GUI run fine on this server.  1.6.3 Terminal runs fine.  

1.6.3 GUI throws this and quits:

localhost:~# jacktrip-1.6.3
qt.qpa.xcb: XKeyboard extension not present on the X server
qt.glx: qglx_findConfig: Failed to finding matching FBConfig for QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize -1, redBufferSize 1, greenBufferSize 1, blueBufferSize 1, alphaBufferSize -1, stencilBufferSize -1, samples -1, swapBehavior QSurfaceFormat::SingleBuffer, swapInterval 1, colorSpace QSurfaceFormat::DefaultColorSpace, profile  QSurfaceFormat::NoProfile)
qt.glx: qglx_findConfig: Failed to finding matching FBConfig for QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize -1, redBufferSize 1, greenBufferSize 1, blueBufferSize 1, alphaBufferSize -1, stencilBufferSize -1, samples -1, swapBehavior QSurfaceFormat::SingleBuffer, swapInterval 1, colorSpace QSurfaceFormat::DefaultColorSpace, profile  QSurfaceFormat::NoProfile)
qt.glx: qglx_findConfig: Failed to finding matching FBConfig for QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize -1, redBufferSize 1, greenBufferSize 1, blueBufferSize 1, alphaBufferSize -1, stencilBufferSize -1, samples -1, swapBehavior QSurfaceFormat::SingleBuffer, swapInterval 1, colorSpace QSurfaceFormat::DefaultColorSpace, profile  QSurfaceFormat::NoProfile)
Could not initialize GLX
Aborted

**Comment by OConnorStP** [comment] 2022-09-16 22:28
Hi all,

This behavior persists in version 1.6.4.

**Comment by cchafe** [comment] 2022-09-16 23:27
I built a 1.6.3 fresh executable on an Rpi and it worked ok starting the GUI from terminal. (#737) 
We should compare executables -- where are the buggy ones from, maybe they're "assets" you downloaded from the releases page?

**Comment by OConnorStP** [comment] 2022-09-17 11:47
ah.  i should be more clear.  this is on a Linode running Debian 11 -- so Intel not ARM CPU.  i just grabbed the binary, dumped it in /usr/local/bin/ and marked it executable.  are there dependencies needing to be loaded these days?

**Comment by ntonnaett** [comment] 2022-09-19 12:06
So this is more of a duplicate of #652.

**Comment by dyfer** [comment] 2022-12-12 08:30
I don't believe this was ever addressed. I can confirm that the static binary of the recent version of Jacktrip crashes on Ubuntu 20.04.

**Comment by ntonnaett** [comment] 2022-12-12 11:17
The problem with static builds is that you never know on what system it will break. There's no stable ABI that we could rely on. We could try to fix those issues when they pop up. But this will probably lead to outdated dependencies on newer systems. IMHO the time to fix issues with the static build is better invested in creating a repo on OBS. But I didn't have enough time to go further down this road. The flathub version is an alternative but the user needs to specify PIPEWIRE_LATENCY for getting low latency. We would need to add a pipewire audio backend to jacktrip to fix this.

I closed the issue because of @OConnorStP 's Edit2 comment that the issue was trying to run a gui jacktrip on a headless system.

**Comment by dyfer** [comment] 2022-12-12 11:30
> I closed the issue because of @OConnorStP 's Edit2 comment that the issue was trying to run a gui jacktrip on a headless system.

I thought that comment meant to disregard the `qt.qpa.xcb:` error since it was existing previously but did not prevent jacktrip from starting _in the previous versions_. I might be understanding that wrong though.

In any case, I was unable to run the recent build (with VS gui, see #845) even when built locally.

**Comment by ntonnaett** [comment] 2023-01-27 20:51
This is probably fixed now with the static build working again.

**Closed by ntonnaett** 2023-01-27 20:51 UTC

**Comment by OConnorStP** [comment] 2023-01-28 12:06
Nope -- just ran 1.7.0 on Debian 11 and got the same error

**Comment by ntonnaett** [comment] 2023-01-28 12:07
Because it was fixed afterwards.

**Comment by OConnorStP** [comment] 2023-01-28 12:08
after 1.7.0?  is there a build i can run?

**Comment by ntonnaett** [comment] 2023-01-28 12:12
https://github.com/jacktrip/jacktrip/actions/runs/4010840845

It should have been fixed with #888 . BTW Why don't you use Debian backports?

**Comment by OConnorStP** [comment] 2023-01-28 12:14
thanks.  i'll give it a try.  i don't use backports because i'm a civilian and have no clue what backports are, just hearing that term for the first time ever.  ;-)

**Comment by ntonnaett** [comment] 2023-01-28 12:16
https://groups.google.com/g/jacktrip-users/c/3RLYvRflczg

I thought that was you. Pardon me!

**Comment by OConnorStP** [comment] 2023-01-28 13:00
<facepalm>  that was me.  chalk the previous comment up to Grumpy Old Man memory failure.  thanks for the reminder.  better answer -- because i'm a civilian and it is a combination of Too Hard and Too Scary to automagically catapult folks into the latest version.  ;-)

good news!   that version cures the Qt problem.  

bad news!  it fails when launching the GUI from the command line and connecting with a Debian command-line Jacktrip 1.5.3 loopback server.  here's the message it leaves.
```

Using JitterBuffer strategy 1
Sleep time  4099  ms at  "2023-01-28T12:35:19"
Connection timed out. Retrying again using exponential backoff
Sleep time  6099  ms at  "2023-01-28T12:35:23"
Connection timed out. Retrying again using exponential backoff 
 - - (which repeats a few times)
JackTrip Server Timed Out!
Stopping JackTrip...
JackTrip Processes STOPPED!
```
and leaves the local client in "waiting for Peer..."  I tried dinking around with various settings but couldn't get past that.  definitely not the same issue.  so... 

as the Author, i concur that this can be closed.
